# GoBinary 指定要使用的Go二进制文件的路径，默认为"go"
GoBinary = "go"
# 环境配置，指定要运行的环境类型，可以是'development'或'production'。默认为'development'
GoEnv = "development"
# 指定要传递给Go命令的环境变量
GoBinaryEnvVars = ["GOPROXY=https://goproxy.cn,direct"]
# 指定可以同时运行'go mod download'的次数，默认是10
GOGetWorkers = 10
# 配置指定Athens将从VCS（版本控制系统）获取模块并在将其持久化到存储后使用的临时目录。
GoGetDir= ""
# 指定所有下载协议路径的并发请求数
ProtocolWorkers = 30
# 日志等级
LogLevel = "debug"
# 指定代理/注册表运行的云提供商
CloudRuntime = "none"
# 是否激活pprof 
EnablePprof = false 
# pprof 指定访问端口
PprofProt = ":3001"
# 用于指定一个包含排除过滤器的文件名，直接从上流拉取，不通过缓存
FilterFile = ""
# 指定爬虫哪里可以
RobotsFile = "robots.txt"
# 指外部网络调用的超时时间
Timeout = 300
# 
StorageType = "mongo"
# 
Port = ":3000"
# 
UnixSocket = ""
# 
GlobalEndpoint = "http://localhost:3001"
# 
# BasicAuthUser= ""
# 
# BasicAuthPass = ""
# 
ForceSSL = false
# 
ValidatorHook = ""
# 
PathPrefix = ""
# 
NETRCPath = ""
# 
GithubToken = ""
# 
HGRCPath = ""
# 
TraceExporter = ""
# 
TraceExporterURL ="http://localhost:14268"
# 
StatsExporter = ""
# 
SumDBs = ["https://sum.golang.org"]
# 指定authens不要校验这些私有模块的数据完整性，直接返回403 Forbidden 
NoSumPatterns= []
# 用于定义Athens在找不到模块版本时的行为         
# sync 在找不到模块时，同步下载模块并将结果返回给客户端
# async 返回404,但是异步将模块存储到后端存储中
# redirect 返回301重定向状态给客户端，重定向的基础URL由DownloadURL指定
# async_redirect 与选项3相同，但异步地将模块存储到后端存储中
# none 如果找不到模块，则返回404，什么都不做
# file:<path> 指向一个HCL文件，该文件根据不同的导入路径指定了上述5个选项中的某个
# custom:<base64-encodeed-hcl> 与选项6相同，但文件完全编码在选项中
DownloadMode = "sync"
# 比对sVCS版本和存储版本，strict严格模式 
NetworkMode = "strict"
# 
DownloadURL = ""
# 并发流控制
SingleFlightType = "redis"
# 索引存储类型
IndexType = "mysql"
# 链接的超时时间
ShutdownTimeout = 60

[SingleFlight]
    [SignleFlight.Redis]
    Endpoint = "127.0.0.1:6379"
    Password = ""
    [SingleFlight.Redis.LockConfig]
        # TTL for the lock in seconds. Defaults to 900 seconds (15 minutes).
        # Env override: ATHENS_REDIS_LOCK_TTL
        TTL = 900
        # Timeout for acquiring the lock in seconds. Defaults to 15 seconds.
        # Env override: ATHENS_REDIS_LOCK_TIMEOUT
        Timeout = 15
        # Max retries while acquiring the lock. Defaults to 10.
        # Env override: ATHENS_REDIS_LOCK_MAX_RETRIES
        MaxRetries = 10
[Storage]
    [Storage.Mongo]
         URL = "mongodb://leimeng:181205@localhost:27017/athens"
         DefaultDBName = "athens"
         CertPaht = ""
         Insecure = false
[Index] 
    [Index.MySQL]
        Protocol = "tcp"
        Host = "localhost"
        Port = 3306
        User = "root"
        Password = "181205"
        Database = "athens"
        [Index.MySQL.Params]
            parseTime = "true"
            timeout = "30s"








